# Generated by Django 5.0.6 on 2024-06-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Hozyain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(default=None, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='NaselenyiPunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TypeNedvig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TypeUchastka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TypeUslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Nedvigimost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('nomer_doma', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=128)),
                ('main_photo', models.CharField(max_length=512)),
                ('obshaya_ploshad', models.FloatField()),
                ('gilaya_ploshad', models.FloatField()),
                ('kuhni_ploshad', models.FloatField()),
                ('uchastka_ploshad', models.FloatField(null=True)),
                ('komnat', models.IntegerField()),
                ('etag', models.IntegerField()),
                ('etagnost', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date_public', models.DateField()),
                ('description', models.CharField(max_length=1024)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.district')),
                ('hozyain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nedvig.hozyain')),
                ('naselenyi_punkt', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.naselenyipunkt')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.street')),
                ('type_nedvig', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.typenedvig')),
                ('type_uchastka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='nedvig.typeuchastka')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoNedvig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('kod_object', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.nedvigimost')),
            ],
        ),
        migrations.CreateModel(
            name='Zayavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=256)),
                ('Phone', models.CharField(max_length=20)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.status')),
                ('type_uslugi', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.typeuslugi')),
            ],
        ),
    ]
