# Generated by Django 5.0.6 on 2024-06-15 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nedvigimost',
            name='date_public',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='komnat',
            field=models.PositiveIntegerField(),
        ),
    ]
