# Generated by Django 5.0.6 on 2024-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0003_alter_nedvigimost_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photonedvig',
            name='path',
            field=models.ImageField(upload_to='nedvig_photo'),
        ),
    ]
