# Generated by Django 5.0.6 on 2024-06-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0004_alter_photonedvig_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='nedvigimost',
            name='type_uslugi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET, to='nedvig.typeuslugi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='type_uchastka',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET, to='nedvig.typeuchastka'),
        ),
    ]
