# Generated by Django 5.0.6 on 2024-06-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0005_nedvigimost_type_uslugi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nedvigimost',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
