# Generated by Django 5.0.6 on 2024-06-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0007_alter_nedvigimost_type_uchastka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nedvigimost',
            name='type_uchastka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='nedvig.typeuchastka'),
        ),
    ]
