# Generated by Django 5.0.6 on 2024-06-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0008_alter_nedvigimost_type_uchastka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hozyain',
            name='email',
            field=models.EmailField(default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET, to='nedvig.status'),
        ),
    ]
