# Generated by Django 5.0.6 on 2024-06-26 06:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0009_alter_hozyain_email_alter_zayavki_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='hozyain',
            name='FIO',
            field=models.CharField(max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='hozyain',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=512, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='hozyain',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='naselenyipunkt',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='date_public',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='etag',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='etagnost',
            field=models.IntegerField(verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='gilaya_ploshad',
            field=models.FloatField(verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='hozyain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nedvig.hozyain', verbose_name='Хозяин'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='komnat',
            field=models.PositiveIntegerField(verbose_name='Комнатность'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='kuhni_ploshad',
            field=models.FloatField(verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='main_photo',
            field=models.ImageField(upload_to='nedvig_photo', verbose_name='Основное фото'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='material',
            field=models.CharField(max_length=128, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='naselenyi_punkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.naselenyipunkt', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='nomer_doma',
            field=models.CharField(max_length=10, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='obshaya_ploshad',
            field=models.FloatField(verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Публиковать'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.street', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='type_nedvig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.typenedvig', verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='type_uchastka',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.SET, to='nedvig.typeuchastka', verbose_name='Тип участка'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='type_uslugi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.typeuslugi', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='nedvigimost',
            name='uchastka_ploshad',
            field=models.FloatField(blank=True, default=1, verbose_name='Площадь участка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photonedvig',
            name='kod_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.nedvigimost', verbose_name='Код объекта'),
        ),
        migrations.AlterField(
            model_name='photonedvig',
            name='path',
            field=models.ImageField(upload_to='nedvig_photo', verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=56, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='typenedvig',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='typeuchastka',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='typeuslugi',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='FIO',
            field=models.CharField(max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='Phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET, to='nedvig.status', verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='type_uslugi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='nedvig.typeuslugi', verbose_name='Тип услуги'),
        ),
    ]
