# Generated by Django 5.0.6 on 2024-06-26 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0010_alter_district_name_alter_hozyain_fio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nedvigimost',
            name='type_uchastka',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET, to='nedvig.typeuchastka', verbose_name='Тип участка'),
        ),
    ]
