# Generated by Django 5.0.6 on 2024-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0011_alter_nedvigimost_type_uchastka'),
    ]

    operations = [
        migrations.AddField(
            model_name='nedvigimost',
            name='kvartira',
            field=models.IntegerField(blank=True, default=None, max_length=5, verbose_name='Квартира'),
        ),
    ]
