# Generated by Django 5.0.6 on 2024-06-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0012_nedvigimost_kvartira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nedvigimost',
            name='uchastka_ploshad',
            field=models.FloatField(blank=True, default=None, verbose_name='Площадь участка'),
        ),
    ]
