# Generated by Django 5.0.6 on 2024-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0015_alter_nedvigimost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nedvigimost',
            name='description',
            field=models.TextField(max_length=4096, verbose_name='Описание'),
        ),
    ]
