# Generated by Django 5.0.6 on 2024-06-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0016_alter_nedvigimost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nedvigimost',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
