# Generated by Django 5.0.6 on 2024-06-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nedvig', '0018_zayavki_kod_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeuslugi',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
    ]
